### ISSUE TITLE
Bugg med win_sock.

### ISSUE THREAD

**Issue by NoRines** [NoRines/Iot-protokoll-labbar#1]
Såg att socket klasserna bara hanterar strängar. Detta fungerar bra när det är text som ska skickas men när det är data som i coap så vill vi inte skicka några extra bytes.
Problemet är att när en sträng skickas via send och sendTo funktionerna så läggs automatiskt en extra byte till i slutet för att gjöra meddelandet null-terminerande. Löste problemet i unix genom att lägga till två funktioner:

* `int send(const char* msg, int msgSize);`
* `int sendTo(const char* msg, int msgSize, const Address& address);`

Commiten där jag löste det för unix är: https://github.com/NoRines/Iot-protokoll-labbar/commit/da61ef0dc99c38d83a3823ad2d2fea06a9be2046

Denna issue är endast för att vi inte ska glömma att göra samma sak i windows.

**Comment by raho1501** [comment]
fixat för windows:
8930e8b129c1551272db60ea10572abd36d9b18d
